// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/finance.proto

package finance

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest1) Reset() {
	*x = LoginRequest1{}
	mi := &file_proto_finance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest1) ProtoMessage() {}

func (x *LoginRequest1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest1.ProtoReflect.Descriptor instead.
func (*LoginRequest1) Descriptor() ([]byte, []int) {
	return file_proto_finance_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest1) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest1) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse1) Reset() {
	*x = LoginResponse1{}
	mi := &file_proto_finance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse1) ProtoMessage() {}

func (x *LoginResponse1) ProtoReflect() protoreflect.Message {
	mi := &file_proto_finance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse1.ProtoReflect.Descriptor instead.
func (*LoginResponse1) Descriptor() ([]byte, []int) {
	return file_proto_finance_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse1) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse1) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse1) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_proto_finance_proto protoreflect.FileDescriptor

const file_proto_finance_proto_rawDesc = "" +
	"\n" +
	"\x13proto/finance.proto\x12\afinance\"A\n" +
	"\rLoginRequest1\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"q\n" +
	"\x0eLoginResponse1\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId2J\n" +
	"\x0efinanceService\x128\n" +
	"\x05Login\x12\x16.finance.LoginRequest1\x1a\x17.finance.LoginResponse1B\x14Z\x12go/finance;financeb\x06proto3"

var (
	file_proto_finance_proto_rawDescOnce sync.Once
	file_proto_finance_proto_rawDescData []byte
)

func file_proto_finance_proto_rawDescGZIP() []byte {
	file_proto_finance_proto_rawDescOnce.Do(func() {
		file_proto_finance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_finance_proto_rawDesc), len(file_proto_finance_proto_rawDesc)))
	})
	return file_proto_finance_proto_rawDescData
}

var file_proto_finance_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_finance_proto_goTypes = []any{
	(*LoginRequest1)(nil),  // 0: finance.LoginRequest1
	(*LoginResponse1)(nil), // 1: finance.LoginResponse1
}
var file_proto_finance_proto_depIdxs = []int32{
	0, // 0: finance.financeService.Login:input_type -> finance.LoginRequest1
	1, // 1: finance.financeService.Login:output_type -> finance.LoginResponse1
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_finance_proto_init() }
func file_proto_finance_proto_init() {
	if File_proto_finance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_finance_proto_rawDesc), len(file_proto_finance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_finance_proto_goTypes,
		DependencyIndexes: file_proto_finance_proto_depIdxs,
		MessageInfos:      file_proto_finance_proto_msgTypes,
	}.Build()
	File_proto_finance_proto = out.File
	file_proto_finance_proto_goTypes = nil
	file_proto_finance_proto_depIdxs = nil
}
